---
name: 📝 Documentation Report
description: Ask us about docs

body:
- type: markdown
  attributes:
    value: >
      **Thank you for wanting to report a problem with ansible-core
      documentation!**


      Please fill out your suggestions below. If the problem seems
      straightforward, feel free to go ahead and
      [submit a pull request] instead!


      ⚠
      Verify first that your issue is not [already reported on
      GitHub][issue search].

      Also test if the latest release and devel branch are affected too.


      **Tip:** If you are seeking community support, please see
      [Communicating with the Ansible community][communication] to
      get in touch and ask questions.



      [communication]:
      https://docs.ansible.com/ansible/devel/community/communication.html

      [issue search]: ../search?q=is%3Aissue&type=issues

      [submit a pull request]:
      https://docs.ansible.com/ansible-core/devel/community/documentation_contributions.html

- type: markdown
  attributes:
    value: >
      **Check the repository for your issue.**

      Source files for Ansible community documentation are
      hosted in different repositories. Please make sure to file an
      issue in the correct project.

      Documentation for modules/plugins/etc that are officially
      supported by the Ansible Core Engineering team is available
      in this (`ansible/ansible`) repository.

      The Installation Guide, Playbook Guide, Developer Guide,
      and other documentation is available in the
      [ansible/ansible-documentation] repository.
      Documentation for other modules/plugins/etc is likely to be
      available in one of the [Ansible Collections][collections index].
      If available in the collection documentation, select the
      **Issue Tracker** button to go directly to the GitHub issues.


      [ansible/ansible-documentation]: /ansible/ansible-documentation

      [collections index]:
      https://docs.ansible.com/ansible/latest/collections/index.html

- type: textarea
  attributes:
    label: Summary
    description: >
      Explain the problem briefly below, add suggestions to wording
      or structure.


      **HINT:** Did you know the documentation has a `View on GitHub`
      link on some pages? Feel free to use it to start a pull request
      right from the GitHub UI!
    placeholder: >-
      I was reading the ansible-core documentation of version X and I'm having
      problems understanding Y. It would be very helpful if that got
      rephrased as Z.
  validations:
    required: true

- type: dropdown
  attributes:
    label: Issue Type
    description: This is a marker for our automatic bot. Do not change it.
    options:
    - Documentation Report
  validations:
    required: true

- type: input
  attributes:
    label: Component Name
    description: >
      Write the short name of the rst file, module, plugin, task or
      feature below, *use your best guess if unsure*.

    placeholder: lib/ansible/modules/copy.py
  validations:
    required: true

- type: textarea
  attributes:
    label: Ansible Version
    description: >-
      Paste verbatim output from `ansible --version` below, under
      the prompt line. Please don't wrap it with triple backticks — your
      whole input will be turned into a code snippet automatically.
    render: console
    value: |
      $ ansible --version
    placeholder: |
      $ ansible --version
      ansible [core 2.11.0b4.post0]  (detached HEAD ref: refs/) last updated 2021/04/02 00:33:35 (GMT +200)
        config file = None
        configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
        ansible python module location = ~/src/github/ansible/ansible/lib/ansible
        ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
        executable location = bin/ansible
        python version = 3.9.0 (default, Oct 26 2020, 13:08:59) [GCC 10.2.0]
        jinja version = 2.11.3
        libyaml = True
  validations:
    required: true

- type: textarea
  attributes:
    label: Configuration
    description: >-
      Paste verbatim output from `ansible-config dump --only-changed -t all` below, under the prompt line.
      (if using a version older than ansible-core 2.12 you should omit the '-t all')
      Please don't wrap it with triple backticks — your
      whole input will be turned into a code snippet automatically.
    render: console
    value: |
      # if using a version older than ansible-core 2.12 you should omit the '-t all'
      $ ansible-config dump --only-changed -t all
    placeholder: |
      # if using a version older than ansible-core 2.12 you should omit the '-t all'
      $ ansible-config dump --only-changed -t all
      DEFAULT_GATHERING(~/src/github/ansible/ansible/ansible.cfg) = smart
      DEFAULT_HOST_LIST(~/src/github/ansible/ansible/ansible.cfg) = ['~/src/github/ansible/ansible/hosts']
      DEFAULT_VAULT_PASSWORD_FILE(~/src/github/ansible/ansible/ansible.cfg) = ~/src/github/ansible/ansible/vault/print-password.sh
  validations:
    required: true

- type: textarea
  attributes:
    label: OS / Environment
    description: >-
      Provide all relevant information below, e.g. OS version,
      browser, etc.
    placeholder: Fedora 33, Firefox etc.
  validations:
    required: true


- type: textarea
  attributes:
    label: Additional Information
    description: |
      Describe how this improves the documentation, e.g. before/after situation or screenshots.

      **HINT:** You can paste https://gist.github.com links for larger files.
    placeholder: >-
      When the improvement is applied, it makes it more straightforward
      to understand X.
  validations:
    required: true


- type: markdown
  attributes:
    value: >
      *One last thing...*


      *Please, complete **all** sections as described, this form
      is [processed automatically by a robot][ansibot help].*


      Thank you for your collaboration!


      [ansibot help]:
      /ansible/ansibotmini#ansibotmini


- type: checkboxes
  attributes:
    label: Code of Conduct
    description: |
      Read the [Ansible Code of Conduct][CoC] first.

      [CoC]: https://docs.ansible.com/ansible/devel/community/code_of_conduct.html?utm_medium=github&utm_source=issue_form--documentation_report.yml
    options:
    - label: I agree to follow the Ansible Code of Conduct
      required: true
...
